import requests


def test_metrics():
    """Should expose cluster metrics as-is."""
    # get cluster metrics exposed by yarnitor
    yarnitor = requests.get('http://web:8080/api/cluster')
    assert yarnitor.ok
    # get last mock metrics generated by YARN
    yarn = requests.get('http://yarn:8088/ws/v1/cluster/metrics?last')
    assert yarn.ok

    # nesting format exposed by YARN
    yarn_metrics = yarn.json()['clusterMetrics']
    # nesting format expected by DataTables in the UI
    yarnitor_metrics = yarnitor.json()['data'][0]

    for key in yarn_metrics.keys():
        assert yarnitor_metrics[key] == yarn_metrics[key], key

def test_applications():
    """Should expose all available YARN applications."""
    resp = requests.get('http://web:8080/api/applications')
    assert resp.ok
